spring:
  profiles:
    active: local
  resources:
    add-mappings: true
  messages:
    basename: i18n/exception
    encoding: UTF-8

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:~/data/chorok2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  jwt:
    secret: abcd!@#$
  h2:
    console:
      enabled: true